version: '3.7'

services:
  dev:
    container_name: motivation_app
    build:
      context: .
      dockerfile: Dockerfile.st
    volumes:
      - .:/streamlit-docker
    tty: True
    env_file: .env
    ports:
      - '8501:8501'
    networks:
      - app-tier

  prd:
    container_name: motivation_app_prd
    build:
      context: .
      dockerfile: Dockerfile.prd
    tty: True
    ports:
      - '8502:8501'
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

