version: '3.7'

services:
  dev:
    container_name: motivation_graph
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/work
    env_file: .env
    tty: True
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

