version: '3.7'

services:
  dev:
    container_name: motivation_graph
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/work
    env_file: .env
    tty: True

  db:
    container_name: mysql_tweet
    build:
      context: ./db/
      dockerfile: Dockerfile
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
    - 3314:3306

